### ISSUE TITLE
cron表达式在config.yaml配置，体力推送需要新增间隔，体力推送运行一遍体力命令推送图片

### ISSUE THREAD

**Issue by rainbowwarmth** [erzaozi/waves-plugin#10]
1.cron表达式在config.yaml配置，每7分钟检查一次感觉是还是有点频繁，建议能自己(Bot主人)设置
2.体力推送间隔是因为鸣潮体力同步到库街区展示需要时间，建议加一个推送过一条，间隔多久推送发第二条
3.体力溢出推送通知后运行一遍体力命令并推送所生成的图片

**Comment by CikeyQi** [comment]
1.TODO
2.体力的推送逻辑已经是恢满之后推送，并在下次使用掉之前不会推送，用掉之后再恢满才会推送第二次
3.我认为体力提醒不需要渲染图片，知道满了就好了
