### ISSUE TITLE
还是喜欢#鸣潮帮助，这样子的方式，能把触发词加回去吗？

### ISSUE THREAD

**Issue by OvertimeBunny** [erzaozi/waves-plugin#14]
还是喜欢#鸣潮帮助，这样子的方式，能把触发词加回去吗？

**Comment by CikeyQi** [comment]
本插件永久不会考虑使用 `#` 开头的指令，目前可以使用 `鸣潮帮助` 唤起插件帮助，个人有其他需求可以自行更改
