### ISSUE TITLE
能否把抽卡记录中的多个卡池合成一张图片展示

### ISSUE THREAD

**Issue by JadeVane** [erzaozi/waves-plugin#17]
可以拼接成一张图片，这样方便一起看，比如这个记录

![2024-06-20_14-21](https://github.com/erzaozi/waves-plugin/assets/34258753/02dd530a-e438-4540-97d4-9fbd5ef5056b)

其实上面标题部分（头像、ID、...）占据了不少空间，而每个卡池的记录中，上方的标题都是一样的，感觉放一起会更好

或者参考 yunzai 原神的抽卡记录，更简洁美观

![2024-06-20_14-20](https://github.com/erzaozi/waves-plugin/assets/34258753/e7498b4e-e26d-4552-b44a-0dfd616a8aeb)

**Comment by CikeyQi** [comment]
你的想法我们已考虑过，目前已知鸣潮有7个卡池，放在一起渲染的图片将会非常大，实际体验并不会很好
