### ISSUE TITLE
~xx面板中声骸词条会被吞并

### ISSUE THREAD

**Issue by YoungHKe** [erzaozi/waves-plugin#21]
相同tag只会显示第一个 比如主词条暴击 副词条暴击不会再显示；又如10级洗出大防御，15级洗出小防御，小防御也不会显示。但是这个好像是taptap的问题TAT

**Comment by Oishiimono** [comment]
+1

**Comment by CikeyQi** [comment]
这是 Taptap 那边的问题，你在 Taptap 查看声骸词条也是这样的，建议向 Taptap 那边进行反馈，让他们修复后这边会自动修复

**Comment by CikeyQi** [comment]
我们这边已经向 Taptap 客服反馈过了，那边还在核实
