### ISSUE TITLE
面板功能在微信群聊中响应命令发送“未知格式...请寻找作者适配...”

### ISSUE THREAD

**Issue by momonini** [erzaozi/waves-plugin#22]
![image](https://github.com/erzaozi/waves-plugin/assets/166779595/9dcbf379-bf89-455c-a41d-a6f536a58162)
[MiaoYz][16:11:14.456][INFO] [WeChatBot] 群消息：[34520013171@chatroom，wxid_b2g
apw6c37wi21][{"type":"text","data":{"text":"~吟霖面板"}}]
[MiaoYz][16:11:14.622][INFO] [喵喵:角色面板][profileDetail][undefined()] ~吟霖面
板
[MiaoYz][16:11:14.627][INFO] [鸣潮-角色面板][character][undefined()] ~吟霖面板
[MiaoYz][16:11:14.794][INFO] 获取可用性成功：账号已过期
[MiaoYz][16:11:14.884][INFO] 获取可用性成功：账号可用
[MiaoYz][16:11:15.222][INFO] 刷新资料成功
[MiaoYz][16:11:15.527][INFO] 获取共鸣者成功
[MiaoYz][16:11:15.715][INFO] 刷新资料成功
[MiaoYz][16:11:16.017][INFO] 获取角色详细信息成功
[MiaoYz][16:11:22.114][MARK] [图片生成][waves-plugin][24次] 632.46KB 6057ms
[MiaoYz][16:11:22.201][INFO] [WeChatBot] 发送群消息：[34520013171@chatroom] {"ty
pe":"text","data":{"text":"未知格式...请寻找作者适配..."}}
[MiaoYz][16:11:22.253][ERRO] ApiRejection {
  code: -60,
  message: 'client not online (cmd: ImgStore.GroupPicUp)'
}
[MiaoYz][16:11:22.564][MARK] [鸣潮-角色面板][character] ~吟霖面板 处理完成 7937m
s

私聊是没问题的
![image](https://github.com/erzaozi/waves-plugin/assets/166779595/33240d37-ab2f-4ab8-a5ae-b16aa0ec16f0)

**Comment by CikeyQi** [comment]
请使用 [TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai) 来连接微信

**Comment by CikeyQi** [comment]
这里的 `寻找作者适配` 指的是寻找适配器开发者，不是插件开发者
