### ISSUE TITLE
抽卡链接识别问题

### ISSUE THREAD

**Issue by molehzy** [erzaozi/waves-plugin#23]
![de988f1b-6284-4b3c-b13c-96215a9fa6fc](https://github.com/user-attachments/assets/1ecec9d2-ee9e-4810-b6f0-82c806208a3b)

**Comment by CikeyQi** [comment]
麻烦提供一下无法识别的完整URL，以便我们复现并确定问题

**Comment by CikeyQi** [comment]
根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整

**Comment by molehzy** [comment]
> 根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整

从浏览器地址栏复制下来依然不行，环境是TRSS+LLOneBot

**Comment by CikeyQi** [comment]
> > 根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整
> 
> 从浏览器地址栏复制下来依然不行，环境是TRSS+LLOneBot

你输入的命令和控制台日志复制粘贴上来给我看看，我这边测试没有任何问题
![test.jpg](https://github.com/user-attachments/assets/01f5f21e-8a3b-4520-a768-ed22a580b3cc)

**Comment by molehzy** [comment]
> 根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整

找到原因了，CQ码不行，消息段才正常
![image](https://github.com/user-attachments/assets/29f76ce2-b1b8-4bf3-951d-8a856e7f414b)

**Comment by molehzy** [comment]
> > 根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整
> 
> 找到原因了，CQ码不行，消息段才正常 ![image](https://private-user-images.githubusercontent.com/34277636/350741990-29f76ce2-b1b8-4bf3-951d-8a856e7f414b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NDY5NzgsIm5iZiI6MTcyMTU0NjY3OCwicGF0aCI6Ii8zNDI3NzYzNi8zNTA3NDE5OTAtMjlmNzZjZTItYjFiOC00YmYzLTk1MWQtOGE4NTZlN2Y0MTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA3MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MWU4MTdmOWY5OWJkMDQyYjcxOGNkNWY3ODQ3YzA0MDlkMzkyMTU4ODc1YzY2MzcyYTIyYWNjMTkzMzBhMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tf8gdziT1ovauTXpvfitBHUq_1U6haWbNWCiE6QXJo8)

可以在这后面加个转义
![image](https://github.com/user-attachments/assets/96562695-57ca-4ad8-81ac-2b4dffb675bb)

**Comment by CikeyQi** [comment]
> > > 根据你刚才提供的URL，我们这边测试是通过的，请再次尝试以确认是否有使用多余的空格或者换行符，复制的URL是否完整
> > 
> > 
> > 找到原因了，CQ码不行，消息段才正常 ![image](https://private-user-images.githubusercontent.com/34277636/350741990-29f76ce2-b1b8-4bf3-951d-8a856e7f414b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NDY5NzgsIm5iZiI6MTcyMTU0NjY3OCwicGF0aCI6Ii8zNDI3NzYzNi8zNTA3NDE5OTAtMjlmNzZjZTItYjFiOC00YmYzLTk1MWQtOGE4NTZlN2Y0MTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA3MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MWU4MTdmOWY5OWJkMDQyYjcxOGNkNWY3ODQ3YzA0MDlkMzkyMTU4ODc1YzY2MzcyYTIyYWNjMTkzMzBhMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tf8gdziT1ovauTXpvfitBHUq_1U6haWbNWCiE6QXJo8)
> 
> 可以在这后面加个转义 ![image](https://private-user-images.githubusercontent.com/34277636/350744290-96562695-57ca-4ad8-81ac-2b4dffb675bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzA4MzEsIm5iZiI6MTcyMTU3MDUzMSwicGF0aCI6Ii8zNDI3NzYzNi8zNTA3NDQyOTAtOTY1NjI2OTUtNTdjYS00YWQ4LTgxYWMtMmI0ZGZmYjY3NWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE0MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZDQxY2FiMzIxNWI3ZWZjNDIzNTdhNjk4YzljYjZhMjM3NThlNWE4NDJmNDcxYmExMjJiZjJkMGVkNTQxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cbqgh5yUZqri-GWOF1TY7J6A2KDqjqcf0yVsCQW3V8o)

Yunzai 本身是不使用 CQ码 的（请参考[README.md](https://github.com/TimeRainStarSky/Yunzai)），而且 LLOneBot 默认使用的是消息段，所以插件去支持 CQ码 是没有意义的
