### ISSUE TITLE
可以移植到nonebot2框架吗

### ISSUE THREAD

**Issue by BraveCowardp** [erzaozi/waves-plugin#26]
很喜欢这个插件的查询角色卡片和声骸得分的功能，想移植部分功能到nonebot2插件，想问一下作者允许移植吗🙏

**Comment by erzaozi** [comment]
感谢你对我们项目的关注和支持！

我们很乐意看到你对项目感兴趣并希望进行移植到其他机器人框架。在进行移植之前，请务必仔细阅读并遵守我们项目 `README` 文件中的许可证页面。按照许可证的规定来移植项目内容，以确保合规。

如果你有任何疑问或需要进一步的澄清，请随时与我们联系。感谢你的理解与合作！

**Comment by CikeyQi** [comment]
> > 感谢你对我们项目的关注和支持！
> > 我们很乐意看到你对项目感兴趣并希望进行移植到其他机器人框架。在进行移植之前，请务必仔细阅读并遵守我们项目 `README` 文件中的许可证页面。按照许可证的规定来移植项目内容，以确保合规。
> > 如果你有任何疑问或需要进一步的澄清，请随时与我们联系。感谢你的理解与合作！
> 
> 佬，我看到README里声明不允许复制和修改resources目录下的文件，如果我直接复制到移植的项目是不是算侵权，以及我是应该自己制作一套资源文件吗

- 如果您是指是渲染模板，我们更希望您能设计出独特的渲染模板和样式。您可以参考我们的功能实现，但我们希望您能自行开发一套模板文件，以确保您的项目在外观和体验上都是独一无二的。
- 如果您是指权重文件，我刚才问了下向我们提供权重文件的佬，他说可以直接用。
- 如果您是指攻略图，我们建议您使用时与对应攻略作者打声招呼，避免侵权的可能。

**Comment by BraveCowardp** [comment]
> > > 感谢你对我们项目的关注和支持！
> > > 我们很乐意看到你对项目感兴趣并希望进行移植到其他机器人框架。在进行移植之前，请务必仔细阅读并遵守我们项目 `README` 文件中的许可证页面。按照许可证的规定来移植项目内容，以确保合规。
> > > 如果你有任何疑问或需要进一步的澄清，请随时与我们联系。感谢你的理解与合作！
> > 
> > 
> > 佬，我看到README里声明不允许复制和修改resources目录下的文件，如果我直接复制到移植的项目是不是算侵权，以及我是应该自己制作一套资源文件吗
> 
> * 如果您是指是渲染模板，我们更希望您能设计出独特的渲染模板和样式。您可以参考我们的功能实现，但我们希望您能自行开发一套模板文件，以确保您的项目在外观和体验上都是独一无二的。
> * 如果您是指权重文件，我刚才问了下向我们提供权重文件的佬，他说可以直接用。
> * 如果您是指攻略图，我们建议您使用时与对应攻略作者打声招呼，避免侵权的可能。

感谢，明白了🙏
