### ISSUE TITLE
签到反馈

### ISSUE THREAD

**Issue by hulinhai2007** [erzaozi/waves-plugin#28]
每日签到的反馈可以具体指向某个QQ发吗，别总鸡号都全部都发一次

**Comment by CikeyQi** [comment]
如有需要可以更改相应代码：

https://github.com/erzaozi/waves-plugin/blob/21be69185bbcfa40b982a7c1383f1cbd907cd958/apps/SignIn.js#L114-L116

更改为

```javascript
 if (autoSignInList.length) { 
     Bot[BotId].pickUser(UserId).sendMsg(`[Waves-Plugin] 自动签到\n今日成功签到 ${success} 个账号`) 
 } 
```

其中`BotId`是机器人QQ，`UserId`是具体指向某个QQ

**Comment by hulinhai2007** [comment]
但因为挂的号多，每个号每天晚上多发一点，嫌烦啊，就是想指定一个号发一次就好了

**Comment by hulinhai2007** [comment]
好的好的，多谢作者～(￣▽￣～)~
