### ISSUE TITLE
大量插件报错

### ISSUE THREAD

**Issue by yimeng-YM** [erzaozi/waves-plugin#32]
![屏幕截图 2024-10-03 111816](https://github.com/user-attachments/assets/cbfebc36-ffb1-4b06-94ef-75465930c969)
![屏幕截图 2024-10-03 111825](https://github.com/user-attachments/assets/a3fe9f72-a567-46ea-94c4-434035316cd1)
昨天发现角色面板一直提示无法获取详细信息，今天卸载插件后重新安装，启动云崽出现大量插件无法加载问题。

**Comment by CikeyQi** [comment]
请按照README中的 `安装插件` 步骤安装依赖
