### ISSUE TITLE
[Bug]: 使用【~卡片】命令时，返回获取我的资料失败，疑似网络问题，请检查控制台日志

### ISSUE THREAD

**Issue by SoraCode-XP** [erzaozi/waves-plugin#34]
### 重要步骤

- [X] 我已核实插件已更新至最新版本，并确认该问题在最新版中依然存在
- [X] 我已仔细阅读 README 文件，并尝试了所有提供的解决方案
- [X] 我已搜索现有的 Issues，并未找到与当前问题相似或相同的反馈

### 插件版本

1.4.5

### 协议端名称

ws 8.18.0

### 问题描述

使用【~卡片】命令时，机器人返回获取【获取我的资料失败，疑似网络问题，请检查控制台日志
】的提示信息

### 期望结果

期望在使用【~卡片】以及其它如【~安可面板】命令时，机器人能够查询指定角色信息或者角色面板信息，并返回渲染后的面板图片

### 复现步骤

1.使用【~登录】命令获取在想登录链接
2.打开在线登录链接并登录账号
3.输入【~卡片】命令

### 启动日志

https://pastebin.com/s2vHdADk

### 问题日志

https://pastebin.com/s2vHdADk

**Comment by CikeyQi** [comment]
已在 `1.4.6` 版本中解决，发送 `~更新` 即可更新插件，重启后生效
