### ISSUE TITLE
[Bug]: 用cf大善人的隧道一直卡转圈

### ISSUE THREAD

**Issue by xingyu42** [erzaozi/waves-plugin#36]
### 重要步骤

- [X] 我已核实插件已更新至最新版本，并确认该问题在最新版中依然存在
- [X] 我已仔细阅读 README 文件，并尝试了所有提供的解决方案
- [X] 我已搜索现有的 Issues，并未找到与当前问题相似或相同的反馈

### 插件版本

最新

### 协议端名称

icqq

### 问题描述

![image](https://github.com/user-attachments/assets/2c75d701-43a1-4882-a26e-313338e62306)
一直卡在这里，挂代理还是卡
日志也一切正常

### 期望结果

正常登录

### 复现步骤

使用~登录获取链接打开网页

### 启动日志

无

### 问题日志

无

**Comment by erzaozi** [comment]
能否提供你登录页面的地址

**Comment by xingyu42** [comment]
> 能否提供你登录页面的地址

https://waves.loxingyu.top/login/

**Comment by erzaozi** [comment]
打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断

**Comment by xingyu42** [comment]
> 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断

请求我是有看过都是200，你看看吧
https://waves.loxingyu.top/login/cmpra608m7

**Comment by erzaozi** [comment]
> > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> 
> 请求我是有看过都是200，你看看吧 https://waves.loxingyu.top/login/cmpra608m7

你可到机器人后台将背景图地址修改为“fast”查看是否能够解决

**Comment by xingyu42** [comment]
> > > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> > 
> > 请求我是有看过都是200，你看看吧 https://waves.loxingyu.top/login/cmpra608m7
> 
> 你可到机器人后台将背景图地址修改为“fast”查看是否能够解决

修改了还是没解决

**Comment by erzaozi** [comment]
> > > > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> > > 
> > > 
> > > 请求我是有看过都是200，你看看吧 https://waves.loxingyu.top/login/cmpra608m7
> > 
> > 
> > 你可到机器人后台将背景图地址修改为“fast”查看是否能够解决
> 
> 修改了还是没解决

能否再提供一次登陆地址

**Comment by xingyu42** [comment]
> > > > > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> > > > 
> > > > 
> > > > 请求我是有看过都是200，你看看吧 https://waves.loxingyu.top/login/cmpra608m7
> > > 
> > > 
> > > 你可到机器人后台将背景图地址修改为“fast”查看是否能够解决
> > 
> > 修改了还是没解决
> 
> 能否再提供一次登陆地址

https://waves.loxingyu.top/login/8o2zx7t7cf

**Comment by CikeyQi** [comment]
> > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> 
> 请求我是有看过都是200，你看看吧
> https://waves.loxingyu.top/login/cmpra608m7
> 

更换网络环境，或者让群友来尝试登录，先确保不是只有你这边有这个问题

**Comment by xingyu42** [comment]
> > > > > > 打开浏览器F12控制台查看网络请求，或者提供我一个可供登录的页面，看起来可能是登陆环境的问题而不是机器人，需要提供更多信息判断
> > > > > 
> > > > > 
> > > > > 请求我是有看过都是200，你看看吧 https://waves.loxingyu.top/login/cmpra608m7
> > > > 
> > > > 
> > > > 你可到机器人后台将背景图地址修改为“fast”查看是否能够解决
> > > 
> > > 
> > > 修改了还是没解决
> > 
> > 
> > 能否再提供一次登陆地址
> 
> https://waves.loxingyu.top/login/8o2zx7t7cf

群友试了也是卡圈了，手机数据电信还是移动都卡

**Comment by xingyu42** [comment]
路由全局挂代理也是卡圈

**Comment by CikeyQi** [comment]
> 路由全局挂代理也是卡圈

请加群反馈
