### ISSUE TITLE
[Bug]: logger.white is not a function 报错

### ISSUE THREAD

**Issue by xingyu42** [erzaozi/waves-plugin#38]
### 重要步骤

- [X] 我已核实插件已更新至最新版本，并确认该问题在最新版中依然存在
- [X] 我已仔细阅读 README 文件，并尝试了所有提供的解决方案
- [X] 我已搜索现有的 Issues，并未找到与当前问题相似或相同的反馈

### 插件版本

最新版本

### 协议端名称

icqq 1.2.6

### 问题描述

**重启报错**
![image](https://github.com/user-attachments/assets/6664123c-fc2f-467b-938b-c6052e0645d6)
![image](https://github.com/user-attachments/assets/ad9aabe3-7d53-4410-86f3-7eaf64ab532c)
无其他
目前看来功能没影响?

### 期望结果

报错消失

### 复现步骤

重启出现

### 启动日志

无

### 问题日志

无

**Comment by CikeyQi** [comment]
用喵崽导致的

**Comment by xingyu42** [comment]
> 用喵崽导致的

咱也不能不用吧

**Comment by xingyu42** [comment]
嘛还是自己改改颜色好了
