### ISSUE TITLE
网页版登录应该如何打开呢

### ISSUE THREAD

**Issue by NdR60A** [erzaozi/waves-plugin#39]
如题，网页版登录应该如何开启，谢谢

**Comment by CikeyQi** [comment]
在锅巴插件的插件管理界面打开对应开关

**Comment by CikeyQi** [comment]
对应的，你也需要正确配置`登录服务公开地址`才能正常使用网页登录功能

**Comment by NdR60A** [comment]
> 对应的，你也需要正确配置`登录服务公开地址`才能正常使用网页登录功能

#感谢回复，我安装了锅巴插件后，发现了设置的地方，毫不意外的卡在了设置 登录服务公开地址 这里😇

**Comment by NdR60A** [comment]
> 如果服务器有公网IP，请直接填写 `http://你的公网IP:25088` 并放行对应端口，如果没有公网IP，请查看README中的 `使用 Cloudflare Tunnel 实现本地化登录服务` 这部分教程

感谢大佬回复，我在服务器放行了对应的端口，却还是无法连接，而且，教程里的第一步，我在锅巴插件配置界面开启网页端登录，重启bot后，127.0.0.1:25088 也无法成功连接

**Comment by CikeyQi** [comment]
请携带 `控制台从机器人启动开始的完整日志`，`锅巴配置页面截图`，`浏览器访问截图`，`服务器安全组截图` 进行反馈，或者加QQ群反馈

**Comment by NdR60A** [comment]
> 请携带 `控制台从机器人启动开始的完整日志`，`锅巴配置页面截图`，`浏览器访问截图`，`服务器安全组截图` 进行反馈，或者加QQ群反馈

已进群👌
