### ISSUE TITLE
转发消息

### ISSUE THREAD

**Issue by 8852690** [erzaozi/waves-plugin#8]
转发消息应该使用e.runtime.common.makeForwardMsg(e, message), 而不是直接用Bot.makeForwardMsg(message), 喵崽的部分插件是使用不了这个方法的, 如ws

**Comment by CikeyQi** [comment]
`Bot.makeForwardMsg` 是最好的方法，在没有 `event` 的情况下仍然可用，所以不打算对其进行兼容
